In [1]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('house_prices.csv')
df.head()
#df = df[['Area', 'Garage', 'Baths', 'Prices']]
#len(df)

Area  Garage  FirePlace  Baths  White Marble  Black Marble  Indian Marble  \
0   164       2          0      2             0             1              0   
1    84       2          0      4             0             0              1   
2   190       2          4      4             1             0              0   
3    75       2          4      4             0             0              1   
4   148       1          4      2             1             0              0   

   Floors  City  Solar  Electric  Fiber  Glass Doors  Swiming Pool  Garden  \
0       0     3      1         1      1            1             0       0   
1       1     2      0         0      0            1             1       1   
2       0     2      0         0      1            0             0       0   
3       1     1      1         1      1            1             1       1   
4       1     2      1         0      0            1             1       1   

   Prices  
0   43800  
1   37550  
2   49500  
3   50075  
4   52400

In [12]:
train_len = (int)(len(df) * 0.8)
test_len = len(df)-train_len
df_train, df_test = df[test_len:], df[:test_len]

In [13]:
len(df_train), len(df_test)

(400000, 100000)

In [14]:
# mb?
# scaler = MinMaxScaler()
# df = scaler.fit_transform(df)

def get_X(df):
    X = np.array(df[['Area', 'Garage', 'Baths']])
    # normalize
    X = X / np.max(X, axis=0)
    # add column of ones
    X = np.hstack([np.ones((X.shape[0], 1)),X])
    return X

def get_y(df):
    y = np.array(df[['Prices']])
    y = np.log(y)
    return y

X_train = get_X(df_train)
y_train = get_y(df_train)

In [15]:
def fit(X, y):
    return np.linalg.inv(X.T @ X) @ X.T @ y

In [16]:
beta = fit(X_train, y_train)
beta

array([[10.34201922],
       [ 0.16282396],
       [ 0.1173131 ],
       [ 0.16317888]])

In [92]:
def predict(X, beta):
    y = np.dot(X, beta)
    return np.exp(y)

In [94]:
X_test = get_X(df_test)
pred_y = predict(X_test, beta)
pred_y

array([[39844.55299969],
       [40364.24389609],
       [43261.32107095],
       ...,
       [39324.07606334],
       [44614.69649227],
       [44866.3414091 ]])

In [103]:
def my_r2_score(y, pred_y):
    a = (y - pred_y)
    b = (y - np.mean(y))
    return 1 - np.dot(a.T, a) / np.dot(b.T, b)

y_test = get_y(df_test)
my_r2_score(np.exp(y_test), pred_y)

array([[0.03054223]])